spring:
  application:
    name: demo-security
  jpa: 
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_secutiry
    username: root
    password: root